/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_smtt_jni_ProcJni */

#ifndef _Included_org_apache_spark_smtt_jni_ProcJni
#define _Included_org_apache_spark_smtt_jni_ProcJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_smtt_jni_ProcJni
 * Method:    setPagesIdle
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_smtt_jni_ProcJni_setPagesIdle
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_apache_spark_smtt_jni_ProcJni
 * Method:    getPageInfos
 * Signature: (Ljava/util/List;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_smtt_jni_ProcJni_getPageInfos
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     org_apache_spark_smtt_jni_ProcJni
 * Method:    getPageInfo
 * Signature: (Lorg/apache/spark/smtt/entity/PageInfo;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_smtt_jni_ProcJni_getPageInfo
  (JNIEnv *, jclass, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
